### ISSUE TITLE
text with "leading-zero" result in wrong value

### ISSUE THREAD

**Issue by EyesOnlyNet** [NaturalIntelligence/fast-xml-parser#10]
Hi, i faced an issue regarding the conversion of "date" and "time" values with leading zeros.

Given: 
```
<?xml version="1.0"?>
<date>02082017</date>
```

Result:
```
{
    "date": 2082017
}
```

Expected:
```
{
    "date": "02082017"
}
```

I need the original, _unprocessed_ values of the XML. So my idea would be, to have an option like `"preserveTextNodeValues": true` or `"convertTextNodeValues": false` to skip the value conversion and keep the original string value.

**Comment by amitguptagwl** [comment]
It can be easily done. Bur unfortunately I don't have any machine now a
days. So you'll have to wait for a month.

**Comment by EyesOnlyNet** [comment]
I've created a pull request for that (#11). Would be nice if you can check it.

**Comment by amitguptagwl** [comment]
Thanks a lot for your valuable time to do the changes. But there is one more task need to run ie "bundle". It'll generate the bundled js for web use in lib folder.

Can you plz update that as well? I'm sorry to be dependent.

**Comment by EyesOnlyNet** [comment]
It is done.
No sorry, if it is only that to proceed.  :smiley:

**Comment by amitguptagwl** [comment]
I have merged the changes. And updated the version. Let me see if I can publish it to npm using my mobile. Otherwise you'll have to update it via github.

Thanks for your effort and time.

*I hope to get laptop in next 2 weeks.

**Comment by EyesOnlyNet** [comment]
Great, thank you very much.

**Comment by nidhi-tandon** [comment]
Is this issue resolved in latest npm update 2.4.3?

**Comment by amitguptagwl** [comment]
Yes. It must be. Let me know if you see any issue.

**Comment by fidelsam1992** [comment]
This issue is not resolved yet ... 
I tried on the latest NPM package 3.11.1
I also tried on the master branch

with this option set : 
var options={
    textNodeConversion:false
}

The output is still wrong

**Comment by amitguptagwl** [comment]
@fidelsam1992 Please refer #99
