### ISSUE TITLE
position of tags is disturbed

### ISSUE THREAD

**Issue by sandeep1756** [NaturalIntelligence/fast-xml-parser#310]
The order of tags gets changed for below set of input:

```
<MyKey>
        <help>
            <p>Some Text:</p>
            <ul>
                <li class="noSpace" style="margin-bottom: 0px;">List Item1 *</li>
                <li class="noSpace" style="margin-bottom: 0px;">List Item2 *</li>
            </ul>
            <p>Some More Text.</p>
            <p>More text<a href="href" title="Click here to view additional information about this topic." alt="Click here to view additional information about this topic." style="line-height: 1.13;color: #0077c8;">here</a>.</p>
        </help>
    </MyKey>
```

I convert to xml, take the first attribute and re-convert value of attribute to xml. However since initial conversion brings all p tags as array, the position is disturbed.
I get output as: 

```
"MyKeyt": {
    "help": "<p>Some Text:</p><p>Some more text.</p><p>More text.<a href=\"href\" title=\"Click here to view additional information about this topic.\" alt=\"Click here to view additional information about this topic.\" style=\"line-height: 1.13;color: #0077c8;\">here</a></p><ul><li class=\"noSpace\" style=\"margin-bottom: 0px;\">List Item1 *</li><li class=\"noSpace\" style=\"margin-bottom: 0px;\">List Item2 *</li></ul>"
```
Is there any way to preserve the position/order of elements?

**Comment by amitguptagwl** [comment]
As keys order in JS object is not maintained, this is expected. However, a new feature is provided in v4 to handle this situation which is not published yet.

**Comment by GitKokoszka** [comment]
It's been some time now. Could you give us some approximate release date of v4?

**Comment by amitguptagwl** [comment]
@GitKokoszka I have already done basic changes for v4 (you might notice them on v4 branch) I have to incorporate new changes and bugs fixed in current version and complete all tests. I'm currently getting no time to work on open source. So cant commit any date.

**Comment by guyca** [comment]
I checked out v4 and added `arrayMode: true` to the options objects used when parsing from and back to XML. Unfortunately, the order of tags is still incorrect.

Has anyone found an alternative solution? I thought of trying https://github.com/Rich-Harris/svg-parser + https://github.com/syntax-tree/hast-util-to-html

**Comment by amitguptagwl** [comment]
@guyca I believe you should have tried `preserveOrder` instead of `arrayMode`. The purpose of both options is completely different. Moreover, as I remember, I had implemented these options only for XML to js obj only yet.

**Comment by guyca** [comment]
Thanks a lot, @amitguptagwl, appreciate your help 👍

**Comment by amitguptagwl** [comment]
`prserveOrder` can be used with fxp v4 to deal such situations
